# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    cocoders.repository.docking_station:
        class: Cocoders\File\CityBike\DockingStationsFileRepository
        arguments: []

    cocoders.use_case.add_docking_station:
        class: Cocoders\UseCase\AddDockingStation\AddDockingStation
        arguments: ["@cocoders.repository.docking_station"]

    cocoders.trm24.parser:
        class: Cocoders\Trm24\Trm24Provider
        arguments: [@cocoders.trm24.client]

    cocoders.add_docking_stations_from_provider:
        class: AppBundle\Command\AddDockingStationsFromProviderCommand
        tags:
            -  { name: console.command }
        arguments: [@cocoders.trm24.parser, @cocoders.use_case.add_docking_station]

    cocoders.trm24.client:
        class: GuzzleHttp\Client
        arguments: []

    cocoders.use_case.update_available_bikes:
        class: Cocoders\UseCase\UpdateAvailableBikes\UpdateAvailableBikes
        arguments: ["@cocoders.repository.docking_station"]

    cocoders.update_available_bikes_from_provider:
        class: AppBundle\Command\UpdateAvailableBikesFromProviderCommand
        tags:
            -  { name: console.command }
        arguments: [@cocoders.trm24.parser, @cocoders.use_case.update_available_bikes]

    cocoders.found_docking_stations:
        class: Cocoders\InMemory\CityBike\FoundDockingStations
        arguments: ["@cocoders.repository.docking_station"]